### ISSUE TITLE
Install 错误

### ISSUE THREAD

**Issue by setsuna** [codeudan/img-editor#2]
D:\webUI\VUE\img-editor-master>cnpm install
- Installing minimalistic-assert@^1.0.0platform unsupported webpack-dev-server@2.4.1 › chokidar@1.6.1 › fsevents@1.1.1 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)

D:\webUI\VUE\img-editor-master\node_modules\.1.6.4@canvas>node "C:\Users\Setsuna\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
d:\webui\vue\img-editor-master\node_modules\.1.6.4@canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No
such file or directory (编译源文件 ..\src\CanvasPattern.cc) [D:\webUI\VUE\img-editor-master\node_modules\.1.6.4@canvas\build
\canvas.vcxproj]
d:\webui\vue\img-editor-master\node_modules\.1.6.4@canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No
such file or directory (编译源文件 ..\src\CanvasGradient.cc) [D:\webUI\VUE\img-editor-master\node_modules\.1.6.4@canvas\buil
d\canvas.vcxproj]
d:\webui\vue\img-editor-master\node_modules\.1.6.4@canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No
such file or directory (编译源文件 ..\src\Canvas.cc) [D:\webUI\VUE\img-editor-master\node_modules\.1.6.4@canvas\build\canvas
.vcxproj]
d:\webui\vue\img-editor-master\node_modules\.1.6.4@canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No
such file or directory (编译源文件 ..\src\CanvasRenderingContext2d.cc) [D:\webUI\VUE\img-editor-master\node_modules\.1.6.4@c
anvas\build\canvas.vcxproj]
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  win_delay_load_hook.cc
d:\webui\vue\img-editor-master\node_modules\.1.6.4@canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No
such file or directory (编译源文件 ..\src\ImageData.cc) [D:\webUI\VUE\img-editor-master\node_modules\.1.6.4@canvas\build\can
vas.vcxproj]
d:\webui\vue\img-editor-master\node_modules\.1.6.4@canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No
such file or directory (编译源文件 ..\src\init.cc) [D:\webUI\VUE\img-editor-master\node_modules\.1.6.4@canvas\build\canvas.v
cxproj]
d:\webui\vue\img-editor-master\node_modules\.1.6.4@canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No
such file or directory (编译源文件 ..\src\Image.cc) [D:\webUI\VUE\img-editor-master\node_modules\.1.6.4@canvas\build\canvas.
vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Setsuna\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Setsuna\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\webUI\VUE\img-editor-master\node_modules\.1.6.4@canvas
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
fabric@1.7.6 › canvas@1.6.4 optional error: Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\Setsuna\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
√ All packages installed (638 packages installed from npm registry, use 35s, speed 132.81kB/s, json 819(4.56MB), tarball 0B)
Recently updated (since 2017-02-20): 29 packages (detail see file D:\webUI\VUE\img-editor-master\node_modules\.recently_updates.txt)
  Today:
    → css-loader@0.25.0 › cssnano@3.10.0 › postcss-discard-duplicates@2.1.0 (03:20:58)
    → fabric@1.7.6 › canvas@1.6.4 (02:46:05)
    → webpack-dev-server@2.4.1 › http-proxy-middleware@0.17.3 › micromatch@2.3.11 › object.omit@2.0.1 › for-own@0.1.5 (09:32:53)
    → webpack-dev-server@2.4.1 › http-proxy-middleware@0.17.3 › micromatch@2.3.11 › object.omit@2.0.1 › for-own@0.1.5 › for-in@1.0.1 (09:29:59)

**Comment by codeudan** [comment]
已经 fix。
